### ISSUE TITLE
OCR can't scan text with underline

### ISSUE THREAD

**Issue by swenner** [BlinkOCR/blinkocr-ios#2]
Arial font with underline can not be scanned.

**Comment by Cerovec** [comment]
Hi,

can you send us an image of the document you're trying to scan? We would be interested in adding this specific case in out test suite. 

Thanks

**Comment by swenner** [comment]
I used the ios sample app and scanned from a screen.

[OCRTestCase.pdf](https://github.com/BlinkOCR/blinkocr-ios/files/58087/OCRTestCase.pdf)

BTW: very bold fonts have issues too (e.g. Impact): http://ufonts.com/fonts/impact.html

**Comment by Cerovec** [comment]
Our team is looking into this.

This specific bold font (Impatc) should not be a problem - we can add it in our OCR model. Here's a [list of all fonts](http://cocoadocs.org/docsets/PPBlinkOCR/1.1.1/Constants/PPOcrFont.html) currently in our SDK.

For the underlined font, the problem is slightly bigger. We either have to remove the line completely to classify each character individually, or we should train our classifier to understand underlined chars. In any case, we should investigate this further to make the conclusions.

You can contact us at info@microblink.com to further explain your use case.

Thanks!
